### ISSUE TITLE
Navigation bar height

### ISSUE THREAD

**Issue by mlaplante** [junglejerry/FirstRepo#18]
Jerry, just a suggestion but the reason your items aren't centered exactly is because you hardcoded a height onto your nav section. I would remove that all together and things will center perfectly then. Otherwise good job

**Comment by junglejerry** [comment]
Cool.  I will remove it now.

**Comment by junglejerry** [comment]
Regarding Assignment Five: How do I get the "Sign Up For Our Newsletter" Field and Legend stuff at the bottom to squeeze and stack with screen adjustment?
